### ISSUE TITLE
add some documentation?

### ISSUE THREAD

**Issue by jiejieTop** [iuncuim/openwrt-imx6ull#1]
such as:
1. Checkout which branch in openwrt
2. How should I operate and compile the image

I put them in the master and use imx6, the compilation error.

**Comment by iuncuim** [comment]
Sorry, try checkout to https://github.com/openwrt/openwrt/commit/9a417fbd0d61cf01d36df0b91ed0490c06dbe5eb
Copy files to OpenWrt root dir. 
Then ./scripts/feeds update -a && ./scripts/feeds install -a
Then make menuconfig, choose Target System Freescale i.MX 6 ULL, Target Profile (somlabs-sd), Target Images ext4, Boot Loaders u-boot-somlabs_visionsom_6ull.
Save and compile with make V=s -j4.

**Comment by jiejieTop** [comment]
Thanks,I have compiled successfully.
But I using - j1 can compile successfully.
```bash
./scripts/feeds update -a && ./scripts/feeds install -a

make V=s -j1
```
Thanks...

**Comment by iuncuim** [comment]
Yep, "install" instead "update". 
-j means host CPU threads.
