### ISSUE TITLE
encountered errors：Build dependency: Please install Python >= 3.5 Build dependency: Please install Python >= 3.5 Build dependency: Please install the Python3 distutils module  Prerequisite check failed. Use FORCE=1 to override. gmake: *** [/home/ljc/tmp/openwrt/include/toplevel.mk:180: staging_dir/host/.prereq-build] Error 1

### ISSUE THREAD

**Issue by scanligithub** [iuncuim/openwrt-imx6ull#3]
Hi iuncuim：
My steps：
1  git clone https://github.com/openwrt/openwrt.git
2  cd openwrt
3  git checkout 76d90a5eaf3b7fc5bb1a1b8626db0e4e2487e876
4  cp your package/boot/* to openwrt
5  cp your target/linux/*  to openwrt
6  ./scripts/feeds update -a && ./scripts/feeds install -a
I encountered errors:
`
Updating feed 'packages' from 'https://github.com/openwrt/packages.git' ...
Already up to date.
Create index file './feeds/packages.index' 
Checking 'working-make'... ok.
Checking 'case-sensitive-fs'... ok.
Checking 'proper-umask'... ok.
Checking 'gcc'... ok.
Checking 'working-gcc'... ok.
Checking 'g++'... ok.
Checking 'working-g++'... ok.
Checking 'ncurses'... ok.
Checking 'perl-data-dumper'... ok.
Checking 'perl-findbin'... ok.
Checking 'perl-file-copy'... ok.
Checking 'perl-file-compare'... ok.
Checking 'perl-thread-queue'... ok.
Checking 'tar'... ok.
Checking 'find'... ok.
Checking 'bash'... ok.
Checking 'xargs'... ok.
Checking 'patch'... ok.
Checking 'diff'... ok.
Checking 'cp'... ok.
Checking 'seq'... ok.
Checking 'awk'... ok.
Checking 'grep'... ok.
Checking 'egrep'... ok.
Checking 'getopt'... ok.
Checking 'stat'... ok.
Checking 'unzip'... ok.
Checking 'bzip2'... ok.
Checking 'wget'... ok.
Checking 'perl'... ok.
Checking 'python2-cleanup'... ok.
Checking 'python'... failed.
Checking 'python3'... failed.
Checking 'python3-distutils'... failed.
Checking 'git'... ok.
Checking 'file'... ok.
Checking 'rsync'... ok.
Checking 'which'... ok.
Checking 'ldconfig-stub'... ok.

Build dependency: Please install Python >= 3.5
Build dependency: Please install Python >= 3.5
Build dependency: Please install the Python3 distutils module

Prerequisite check failed. Use FORCE=1 to override.
gmake: *** [/home/ljc/tmp/openwrt/include/toplevel.mk:180: staging_dir/host/.prereq-build] Error 1
`

But when checkout main branch,
./scripts/feeds update -a && ./scripts/feeds install -a
run successfully and no error message.

**Comment by iuncuim** [comment]
Hi. I think that the openwrt build system in this commit doesn't know anything about python 3.10 and 3.11. Try using a more recent commit or find where the check failed.

**Comment by scanligithub** [comment]
Thank you iuncuim:
I changed step：3 from 
`git checkout 76d90a5eaf3b7fc5bb1a1b8626db0e4e2487e876`
 to
`git checkout  openwrt-21.02`
and compiled successfully
